"""Map ID -> display name lookup.

Sourced from `pret/pokered`'s `constants/map_constants.asm`, which defines
map IDs by their position in a single `const_def` block (map ID == index
into that block, starting at $00).

`pokered` doesn't ship one free-text display name per map the way it does
for items and species - indoor maps in particular have no separate
name-string data file. Names here are instead derived mechanically from
each map's constant identifier: underscores become spaces and each word is
title-cased (e.g. `ROUTE_1` -> "Route 1", `REDS_HOUSE_1F` -> "Reds House
1F"). This is deterministic and still fully sourced from the disassembly
identifiers, though it doesn't restore apostrophes those identifiers drop
(e.g. "Reds" rather than "Red's").
"""

_MAP_CONSTANTS: list[str] = [
    "PALLET_TOWN",
    "VIRIDIAN_CITY",
    "PEWTER_CITY",
    "CERULEAN_CITY",
    "LAVENDER_TOWN",
    "VERMILION_CITY",
    "CELADON_CITY",
    "FUCHSIA_CITY",
    "CINNABAR_ISLAND",
    "INDIGO_PLATEAU",
    "SAFFRON_CITY",
    "UNUSED_MAP_0B",
    "ROUTE_1",
    "ROUTE_2",
    "ROUTE_3",
    "ROUTE_4",
    "ROUTE_5",
    "ROUTE_6",
    "ROUTE_7",
    "ROUTE_8",
    "ROUTE_9",
    "ROUTE_10",
    "ROUTE_11",
    "ROUTE_12",
    "ROUTE_13",
    "ROUTE_14",
    "ROUTE_15",
    "ROUTE_16",
    "ROUTE_17",
    "ROUTE_18",
    "ROUTE_19",
    "ROUTE_20",
    "ROUTE_21",
    "ROUTE_22",
    "ROUTE_23",
    "ROUTE_24",
    "ROUTE_25",
    "REDS_HOUSE_1F",
    "REDS_HOUSE_2F",
    "BLUES_HOUSE",
    "OAKS_LAB",
    "VIRIDIAN_POKECENTER",
    "VIRIDIAN_MART",
    "VIRIDIAN_SCHOOL_HOUSE",
    "VIRIDIAN_NICKNAME_HOUSE",
    "VIRIDIAN_GYM",
    "DIGLETTS_CAVE_ROUTE_2",
    "VIRIDIAN_FOREST_NORTH_GATE",
    "ROUTE_2_TRADE_HOUSE",
    "ROUTE_2_GATE",
    "VIRIDIAN_FOREST_SOUTH_GATE",
    "VIRIDIAN_FOREST",
    "MUSEUM_1F",
    "MUSEUM_2F",
    "PEWTER_GYM",
    "PEWTER_NIDORAN_HOUSE",
    "PEWTER_MART",
    "PEWTER_SPEECH_HOUSE",
    "PEWTER_POKECENTER",
    "MT_MOON_1F",
    "MT_MOON_B1F",
    "MT_MOON_B2F",
    "CERULEAN_TRASHED_HOUSE",
    "CERULEAN_TRADE_HOUSE",
    "CERULEAN_POKECENTER",
    "CERULEAN_GYM",
    "BIKE_SHOP",
    "CERULEAN_MART",
    "MT_MOON_POKECENTER",
    "CERULEAN_TRASHED_HOUSE_COPY",
    "ROUTE_5_GATE",
    "UNDERGROUND_PATH_ROUTE_5",
    "DAYCARE",
    "ROUTE_6_GATE",
    "UNDERGROUND_PATH_ROUTE_6",
    "UNDERGROUND_PATH_ROUTE_6_COPY",
    "ROUTE_7_GATE",
    "UNDERGROUND_PATH_ROUTE_7",
    "UNDERGROUND_PATH_ROUTE_7_COPY",
    "ROUTE_8_GATE",
    "UNDERGROUND_PATH_ROUTE_8",
    "ROCK_TUNNEL_POKECENTER",
    "ROCK_TUNNEL_1F",
    "POWER_PLANT",
    "ROUTE_11_GATE_1F",
    "DIGLETTS_CAVE_ROUTE_11",
    "ROUTE_11_GATE_2F",
    "ROUTE_12_GATE_1F",
    "BILLS_HOUSE",
    "VERMILION_POKECENTER",
    "POKEMON_FAN_CLUB",
    "VERMILION_MART",
    "VERMILION_GYM",
    "VERMILION_PIDGEY_HOUSE",
    "VERMILION_DOCK",
    "SS_ANNE_1F",
    "SS_ANNE_2F",
    "SS_ANNE_3F",
    "SS_ANNE_B1F",
    "SS_ANNE_BOW",
    "SS_ANNE_KITCHEN",
    "SS_ANNE_CAPTAINS_ROOM",
    "SS_ANNE_1F_ROOMS",
    "SS_ANNE_2F_ROOMS",
    "SS_ANNE_B1F_ROOMS",
    "UNUSED_MAP_69",
    "UNUSED_MAP_6A",
    "UNUSED_MAP_6B",
    "VICTORY_ROAD_1F",
    "UNUSED_MAP_6D",
    "UNUSED_MAP_6E",
    "UNUSED_MAP_6F",
    "UNUSED_MAP_70",
    "LANCES_ROOM",
    "UNUSED_MAP_72",
    "UNUSED_MAP_73",
    "UNUSED_MAP_74",
    "UNUSED_MAP_75",
    "HALL_OF_FAME",
    "UNDERGROUND_PATH_NORTH_SOUTH",
    "CHAMPIONS_ROOM",
    "UNDERGROUND_PATH_WEST_EAST",
    "CELADON_MART_1F",
    "CELADON_MART_2F",
    "CELADON_MART_3F",
    "CELADON_MART_4F",
    "CELADON_MART_ROOF",
    "CELADON_MART_ELEVATOR",
    "CELADON_MANSION_1F",
    "CELADON_MANSION_2F",
    "CELADON_MANSION_3F",
    "CELADON_MANSION_ROOF",
    "CELADON_MANSION_ROOF_HOUSE",
    "CELADON_POKECENTER",
    "CELADON_GYM",
    "GAME_CORNER",
    "CELADON_MART_5F",
    "GAME_CORNER_PRIZE_ROOM",
    "CELADON_DINER",
    "CELADON_CHIEF_HOUSE",
    "CELADON_HOTEL",
    "LAVENDER_POKECENTER",
    "POKEMON_TOWER_1F",
    "POKEMON_TOWER_2F",
    "POKEMON_TOWER_3F",
    "POKEMON_TOWER_4F",
    "POKEMON_TOWER_5F",
    "POKEMON_TOWER_6F",
    "POKEMON_TOWER_7F",
    "MR_FUJIS_HOUSE",
    "LAVENDER_MART",
    "LAVENDER_CUBONE_HOUSE",
    "FUCHSIA_MART",
    "FUCHSIA_BILLS_GRANDPAS_HOUSE",
    "FUCHSIA_POKECENTER",
    "WARDENS_HOUSE",
    "SAFARI_ZONE_GATE",
    "FUCHSIA_GYM",
    "FUCHSIA_MEETING_ROOM",
    "SEAFOAM_ISLANDS_B1F",
    "SEAFOAM_ISLANDS_B2F",
    "SEAFOAM_ISLANDS_B3F",
    "SEAFOAM_ISLANDS_B4F",
    "VERMILION_OLD_ROD_HOUSE",
    "FUCHSIA_GOOD_ROD_HOUSE",
    "POKEMON_MANSION_1F",
    "CINNABAR_GYM",
    "CINNABAR_LAB",
    "CINNABAR_LAB_TRADE_ROOM",
    "CINNABAR_LAB_METRONOME_ROOM",
    "CINNABAR_LAB_FOSSIL_ROOM",
    "CINNABAR_POKECENTER",
    "CINNABAR_MART",
    "CINNABAR_MART_COPY",
    "INDIGO_PLATEAU_LOBBY",
    "COPYCATS_HOUSE_1F",
    "COPYCATS_HOUSE_2F",
    "FIGHTING_DOJO",
    "SAFFRON_GYM",
    "SAFFRON_PIDGEY_HOUSE",
    "SAFFRON_MART",
    "SILPH_CO_1F",
    "SAFFRON_POKECENTER",
    "MR_PSYCHICS_HOUSE",
    "ROUTE_15_GATE_1F",
    "ROUTE_15_GATE_2F",
    "ROUTE_16_GATE_1F",
    "ROUTE_16_GATE_2F",
    "ROUTE_16_FLY_HOUSE",
    "ROUTE_12_SUPER_ROD_HOUSE",
    "ROUTE_18_GATE_1F",
    "ROUTE_18_GATE_2F",
    "SEAFOAM_ISLANDS_1F",
    "ROUTE_22_GATE",
    "VICTORY_ROAD_2F",
    "ROUTE_12_GATE_2F",
    "VERMILION_TRADE_HOUSE",
    "DIGLETTS_CAVE",
    "VICTORY_ROAD_3F",
    "ROCKET_HIDEOUT_B1F",
    "ROCKET_HIDEOUT_B2F",
    "ROCKET_HIDEOUT_B3F",
    "ROCKET_HIDEOUT_B4F",
    "ROCKET_HIDEOUT_ELEVATOR",
    "UNUSED_MAP_CC",
    "UNUSED_MAP_CD",
    "UNUSED_MAP_CE",
    "SILPH_CO_2F",
    "SILPH_CO_3F",
    "SILPH_CO_4F",
    "SILPH_CO_5F",
    "SILPH_CO_6F",
    "SILPH_CO_7F",
    "SILPH_CO_8F",
    "POKEMON_MANSION_2F",
    "POKEMON_MANSION_3F",
    "POKEMON_MANSION_B1F",
    "SAFARI_ZONE_EAST",
    "SAFARI_ZONE_NORTH",
    "SAFARI_ZONE_WEST",
    "SAFARI_ZONE_CENTER",
    "SAFARI_ZONE_CENTER_REST_HOUSE",
    "SAFARI_ZONE_SECRET_HOUSE",
    "SAFARI_ZONE_WEST_REST_HOUSE",
    "SAFARI_ZONE_EAST_REST_HOUSE",
    "SAFARI_ZONE_NORTH_REST_HOUSE",
    "CERULEAN_CAVE_2F",
    "CERULEAN_CAVE_B1F",
    "CERULEAN_CAVE_1F",
    "NAME_RATERS_HOUSE",
    "CERULEAN_BADGE_HOUSE",
    "UNUSED_MAP_E7",
    "ROCK_TUNNEL_B1F",
    "SILPH_CO_9F",
    "SILPH_CO_10F",
    "SILPH_CO_11F",
    "SILPH_CO_ELEVATOR",
    "UNUSED_MAP_ED",
    "UNUSED_MAP_EE",
    "TRADE_CENTER",
    "COLOSSEUM",
    "UNUSED_MAP_F1",
    "UNUSED_MAP_F2",
    "UNUSED_MAP_F3",
    "UNUSED_MAP_F4",
    "LORELEIS_ROOM",
    "BRUNOS_ROOM",
    "AGATHAS_ROOM",
]

_MAP_NAMES: dict[int, str] = {
    map_id: " ".join(word.title() for word in const_name.split("_"))
    for map_id, const_name in enumerate(_MAP_CONSTANTS)
}

# Total map ID slots `pokered`'s `constants/map_constants.asm` `const_def`
# block defines, `UNUSED_MAP_*` placeholders included - `rom_maps.py` uses
# this as the upper bound when resolving every map through the ROM's own
# header tables.
MAP_COUNT = len(_MAP_CONSTANTS)


def map_name(map_id: int) -> str:
    """Resolve a Pokemon Red map ID to its display name.

    Unknown/out-of-range IDs return a placeholder string instead of
    raising, so callers building game-state text never crash on a bad ID.
    """
    return _MAP_NAMES.get(map_id, f"Unknown Map ({map_id})")


def is_unused_map(map_id: int) -> bool:
    """True if `map_id` is one of `pokered`'s unused/placeholder map slots.

    These IDs still resolve through the ROM's header pointer/bank tables to
    *something*, but that something is padding: several consecutive unused
    slots alias the exact same (bank, address) pair and decode to
    implausible block/record data (e.g. a 240x92-block grid, or a warp
    count in the hundreds) rather than a real map - confirmed by
    `rom_maps.py`'s own parse against this repo's `pokemon_red.gb`.
    Out-of-range IDs count as unused so callers can filter with this alone.
    """
    if 0 <= map_id < len(_MAP_CONSTANTS):
        return _MAP_CONSTANTS[map_id].startswith("UNUSED_MAP")
    return True
