"""Species ID -> display name lookup.

Sourced from `pret/pokered`, the canonical Pokemon Red/Blue disassembly:
- IDs: `constants/pokemon_constants.asm`, in internal index order. This is
  the order species are stored in Pokemon Red's RAM (party structs, wild/
  trainer encounters), which is *not* National Pokedex order.
- Display text: `data/pokemon/names.asm`, including "MISSINGNO." for the
  unused internal-index slots (`const_skip` in `pokemon_constants.asm`) -
  those are real, game-rendered names for glitch Pokemon, not gaps filled
  in here.
"""

_SPECIES_NAMES: dict[int, str] = {
    0x01: "RHYDON",
    0x02: "KANGASKHAN",
    0x03: "NIDORAN♂",
    0x04: "CLEFAIRY",
    0x05: "SPEAROW",
    0x06: "VOLTORB",
    0x07: "NIDOKING",
    0x08: "SLOWBRO",
    0x09: "IVYSAUR",
    0x0A: "EXEGGUTOR",
    0x0B: "LICKITUNG",
    0x0C: "EXEGGCUTE",
    0x0D: "GRIMER",
    0x0E: "GENGAR",
    0x0F: "NIDORAN♀",
    0x10: "NIDOQUEEN",
    0x11: "CUBONE",
    0x12: "RHYHORN",
    0x13: "LAPRAS",
    0x14: "ARCANINE",
    0x15: "MEW",
    0x16: "GYARADOS",
    0x17: "SHELLDER",
    0x18: "TENTACOOL",
    0x19: "GASTLY",
    0x1A: "SCYTHER",
    0x1B: "STARYU",
    0x1C: "BLASTOISE",
    0x1D: "PINSIR",
    0x1E: "TANGELA",
    0x1F: "MISSINGNO.",
    0x20: "MISSINGNO.",
    0x21: "GROWLITHE",
    0x22: "ONIX",
    0x23: "FEAROW",
    0x24: "PIDGEY",
    0x25: "SLOWPOKE",
    0x26: "KADABRA",
    0x27: "GRAVELER",
    0x28: "CHANSEY",
    0x29: "MACHOKE",
    0x2A: "MR.MIME",
    0x2B: "HITMONLEE",
    0x2C: "HITMONCHAN",
    0x2D: "ARBOK",
    0x2E: "PARASECT",
    0x2F: "PSYDUCK",
    0x30: "DROWZEE",
    0x31: "GOLEM",
    0x32: "MISSINGNO.",
    0x33: "MAGMAR",
    0x34: "MISSINGNO.",
    0x35: "ELECTABUZZ",
    0x36: "MAGNETON",
    0x37: "KOFFING",
    0x38: "MISSINGNO.",
    0x39: "MANKEY",
    0x3A: "SEEL",
    0x3B: "DIGLETT",
    0x3C: "TAUROS",
    0x3D: "MISSINGNO.",
    0x3E: "MISSINGNO.",
    0x3F: "MISSINGNO.",
    0x40: "FARFETCH'D",
    0x41: "VENONAT",
    0x42: "DRAGONITE",
    0x43: "MISSINGNO.",
    0x44: "MISSINGNO.",
    0x45: "MISSINGNO.",
    0x46: "DODUO",
    0x47: "POLIWAG",
    0x48: "JYNX",
    0x49: "MOLTRES",
    0x4A: "ARTICUNO",
    0x4B: "ZAPDOS",
    0x4C: "DITTO",
    0x4D: "MEOWTH",
    0x4E: "KRABBY",
    0x4F: "MISSINGNO.",
    0x50: "MISSINGNO.",
    0x51: "MISSINGNO.",
    0x52: "VULPIX",
    0x53: "NINETALES",
    0x54: "PIKACHU",
    0x55: "RAICHU",
    0x56: "MISSINGNO.",
    0x57: "MISSINGNO.",
    0x58: "DRATINI",
    0x59: "DRAGONAIR",
    0x5A: "KABUTO",
    0x5B: "KABUTOPS",
    0x5C: "HORSEA",
    0x5D: "SEADRA",
    0x5E: "MISSINGNO.",
    0x5F: "MISSINGNO.",
    0x60: "SANDSHREW",
    0x61: "SANDSLASH",
    0x62: "OMANYTE",
    0x63: "OMASTAR",
    0x64: "JIGGLYPUFF",
    0x65: "WIGGLYTUFF",
    0x66: "EEVEE",
    0x67: "FLAREON",
    0x68: "JOLTEON",
    0x69: "VAPOREON",
    0x6A: "MACHOP",
    0x6B: "ZUBAT",
    0x6C: "EKANS",
    0x6D: "PARAS",
    0x6E: "POLIWHIRL",
    0x6F: "POLIWRATH",
    0x70: "WEEDLE",
    0x71: "KAKUNA",
    0x72: "BEEDRILL",
    0x73: "MISSINGNO.",
    0x74: "DODRIO",
    0x75: "PRIMEAPE",
    0x76: "DUGTRIO",
    0x77: "VENOMOTH",
    0x78: "DEWGONG",
    0x79: "MISSINGNO.",
    0x7A: "MISSINGNO.",
    0x7B: "CATERPIE",
    0x7C: "METAPOD",
    0x7D: "BUTTERFREE",
    0x7E: "MACHAMP",
    0x7F: "MISSINGNO.",
    0x80: "GOLDUCK",
    0x81: "HYPNO",
    0x82: "GOLBAT",
    0x83: "MEWTWO",
    0x84: "SNORLAX",
    0x85: "MAGIKARP",
    0x86: "MISSINGNO.",
    0x87: "MISSINGNO.",
    0x88: "MUK",
    0x89: "MISSINGNO.",
    0x8A: "KINGLER",
    0x8B: "CLOYSTER",
    0x8C: "MISSINGNO.",
    0x8D: "ELECTRODE",
    0x8E: "CLEFABLE",
    0x8F: "WEEZING",
    0x90: "PERSIAN",
    0x91: "MAROWAK",
    0x92: "MISSINGNO.",
    0x93: "HAUNTER",
    0x94: "ABRA",
    0x95: "ALAKAZAM",
    0x96: "PIDGEOTTO",
    0x97: "PIDGEOT",
    0x98: "STARMIE",
    0x99: "BULBASAUR",
    0x9A: "VENUSAUR",
    0x9B: "TENTACRUEL",
    0x9C: "MISSINGNO.",
    0x9D: "GOLDEEN",
    0x9E: "SEAKING",
    0x9F: "MISSINGNO.",
    0xA0: "MISSINGNO.",
    0xA1: "MISSINGNO.",
    0xA2: "MISSINGNO.",
    0xA3: "PONYTA",
    0xA4: "RAPIDASH",
    0xA5: "RATTATA",
    0xA6: "RATICATE",
    0xA7: "NIDORINO",
    0xA8: "NIDORINA",
    0xA9: "GEODUDE",
    0xAA: "PORYGON",
    0xAB: "AERODACTYL",
    0xAC: "MISSINGNO.",
    0xAD: "MAGNEMITE",
    0xAE: "MISSINGNO.",
    0xAF: "MISSINGNO.",
    0xB0: "CHARMANDER",
    0xB1: "SQUIRTLE",
    0xB2: "CHARMELEON",
    0xB3: "WARTORTLE",
    0xB4: "CHARIZARD",
    0xB5: "MISSINGNO.",
    0xB6: "MISSINGNO.",
    0xB7: "MISSINGNO.",
    0xB8: "MISSINGNO.",
    0xB9: "ODDISH",
    0xBA: "GLOOM",
    0xBB: "VILEPLUME",
    0xBC: "BELLSPROUT",
    0xBD: "WEEPINBELL",
    0xBE: "VICTREEBEL",
}


def species_name(species_id: int) -> str:
    """Resolve a Pokemon Red species ID (internal index) to its display name.

    Unknown/out-of-range IDs return a placeholder string instead of
    raising, so callers building game-state text never crash on a bad ID.
    """
    return _SPECIES_NAMES.get(species_id, f"Unknown Species ({species_id})")
